[target."aarch64-linux-ohos"]
linker = "/Users/cyc/Library/Huawei/sdk/native/3.0.0.0/llvm/bin/clang"

[target."aarch64-linux-ohos-win"]
linker = "D:/programs/OpenHarmonySDK/legacy/native/3.0.0.0/llvm/bin/clang.exe"
