[package]
name = "rust"
version = "0.1.0"
authors = ["Chen Yunchuan <chenych11@gmail.com>"]

[dependencies]
jni = "0.5.2"

[lib]
crate_type = ["cdylib"]
#crate_type = ["staticlib", "cdylib"]
#crate_type = ["staticlib"]
